name: External Access Test

on:
  workflow_dispatch:  # This allows the workflow to be manually triggered

jobs:
  test-connection:
    runs-on: ubuntu-latest
    container:
      image: selenium/standalone-chrome:122.0  # Specify the Chrome version

    steps:
      - name: Check connectivity to Google
        run: |
          curl -s https://testingautomation.secure.stagenonprofitsoapbox.com/ > /dev/null
          if [ $? -eq 0 ]; then
            echo "Successfully accessed Soapbox Engage."
          else
            echo "Failed to access Soapbox Engage."
            exit 1
          fi
